version: '3'


services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: my_listproject
    volumes:
      - .:/my_listproject
    ports:
      - "8000"
    depends_on:
      - db

  db:
      image: postgres:latest
      container_name: postgre
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - DOCKER=True
        - POSTGRES_DB=shopdatabase
        - DB_USER=circleci
        - DB_PASSWORD='password'
volumes:
  postgres_data:
