version: '3'


services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: my_listproject
    ports:
      - "8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=ul5@2n@hw=cq_(+&_axxixuig05qj08u-jh1&-q*)bckws&fbd
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=circle_test
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  db:
      image: postgres:latest
      container_name: postgre
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - DOCKER=True
        - POSTGRES_DB=shopdatabase
        - DB_USER=postgres
        - DB_PASSWORD='password'
volumes:
  postgres_data:
