version: '3'


services:
  web:
    build: .
    container_name: my_listproject
<<<<<<< HEAD
    command: gunicorn listproject.wsgi:application --bind 0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - .:/my_listproject
=======
    ports:
      - "8000"
>>>>>>> 3bcba8ca754f5b048bfdf58cb58e955b402b8735
    environment:
      - DEBUG=1
      - SECRET_KEY=ul5@2n@hw=cq_(+&_axxixuig05qj08u-jh1&-q*)bckws&fbd
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=circle_test
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - 8000
    volumes:
      - ./etc/nginx/sites-available/myapp:/etc/nginx/sites-enabled/myapp
    depends_on:
      - web
    networks:
      - nginx_network

  db:
      image: postgres:latest
      container_name: postgre
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - DOCKER=True
        - POSTGRES_DB=circle_test
        - POSTGRES_USER=kaberere
        - POSTGRES_PASSWORD=password
      networks:
        - database_network
networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  postgres_data:
