---     #Preferable syntax to start .yml file
- name: Installation          # Name of the task to be performed in the destinaton host
  hosts: all
  #host = All -- Incase you have many servers in your ssh.cfg file
  #hosts: localhost
  become: True        #Makes you an user for the remote host
  tasks:        # Tasks to be performed
    - name: Create file
      copy:     # Ansible module
      #If you wanted to copy from a particular source, you would have used 'src:' instead of 'content'
        content: Create \n      # What is to be written in the test.txt
        dest: /tmp/test.txt

    - name: Install dependancies
      apt: name={{ item }} state=installed
      with_items: # Looping thro' the depedencies to be installed
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
