# Python CircleCI 2.0 configuration file

#should always start with a version number-issues warnings about breaking changes
version: 1

# jobs refer to a single execution of the build
jobs:
  # build is the name of the job....they can be multiple and unique
  build:
    # builds occur in a docker container
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:latest

    working_directory: ~/listproject

    # series/ list of steps done for the build
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            virtualenv venv --python=python3
            . venv/bin/activate
            pip3 install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 manage.py test
            tox
            coverage run --source='.' manage.py test
            coverage report
