---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: AppRepo

# the base path to install to.
install_root: /app


# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ install_root }}/{{ project_name }}/listproject"

# the dns name or names (space separated) for your server
server_name: remindershoplist.duckdns.org www.remindershoplist.duckdns.org



system_packages:
  - git
  - nginx
  - gunicorn
  - python3-pip
  - python3-dev
  - libpq-dev
  - postgresql
  - postgresql-server-dev-all
  - python3-psycopg2
  - python-certbot-nginx
